name: Bug Report
description: Report a bug or unexpected behavior in libAES67.
title: "[BUG]: <INSERT_TITLE>"
labels: ["needs-triage", "type: bug"]
assignees: 
  - N3v1
body:
  - type: markdown
    attributes:
      value: |
        ### Bug Report

        Thank you for reporting a bug in libAES67! To help us address the issue effectively, please provide as much detail as possible.
        Include steps to reproduce, expected vs actual behavior, and any relevant logs or error messages.
        If you have a minimal reproducible example, please include it as well. Clear and concise reports help us resolve issues faster.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS version, architecture, and build tools
      placeholder: e.g. macOS 15.5, x86_64, GCC 13.1, CMake 3.29
      value: |
        - OS:
        - Arch:
        - Clang:
        - MSVC:
        - GCC:
        - CMake:
    validations:
      required: true

  - type: dropdown
    id: layer
    attributes:
      label: Affected Layer
      description: Select the part of libAES67 you think is affected.
      options:
        - audio
        - network
        - clock-sync
        - sdp
        - api
        - build
        - platform
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise summary of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Build the project
        2. Run the binary
        3. Observe the crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Output
      description: Paste logs, backtraces, or error messages.
      placeholder: Paste any relevant runtime output or crash logs.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Include any other relevant details or context.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you requested.
      options:
        - label: I have searched the existing issues
    validations:
      required: true